code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cssho.vscode-svgviewer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dotdevru.prettier-java
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension HookyQR.beautify
code --install-extension hoovercj.vscode-power-mode
code --install-extension marp-team.marp-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension silvenon.mdx
code --install-extension Tyriar.sort-lines
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wingrunr21.vscode-ruby